# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'test-mk-arm-serviceConn'
    subscriptionId: '4dd5454f-42b5-471f-91d0-caabc2582f39'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test-mk'
    location: 'Germany West Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/ZOI-MKegler/test-arm-ado/master/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/ZOI-MKegler/test-arm-ado/master/azuredeploy.parameters.dev.json'
    #overrideParameters: '-storagePrefix mk2 -dataFactoryPrefix mkdf'
    deploymentMode: 'Incremental'
    deploymentName: 'testdeploymentfromado'